name: No Response
on:
  issue_comment:
    types: [created]
  schedule:
    - cron: '0 0 3 * *'

jobs:
  noResponse:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          token: ${{ github.token }}
          closeComment: |
            Sự cố này đã được tự động đóng lại vì không có phản hồi nào khác quá lâu.
            Vui lòng mở lại vấn đề này nếu bạn vẫn tiếp tục gặp lỗi tương tự sau khi cập nhật bản mới nhất.
          daysUntilClose: 25
          
          
